import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
=======
import { Figtree } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "./components/Navbar";

const geistSans = Figtree({
>>>>>>> f2cf57e (Initialize AgriPath project with essential files and configurations)
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

<<<<<<< HEAD
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
export const metadata: Metadata = {
  title: "AgriPath",
  description: "Connect with agricultural investment opportunities",
>>>>>>> f2cf57e (Initialize AgriPath project with essential files and configurations)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
=======
      <body className={`${geistSans.variable} antialiased`}>
>>>>>>> f2cf57e (Initialize AgriPath project with essential files and configurations)
        {children}
      </body>
    </html>
  );
}
